Update Readme with the working .env url
devinit/DIwebsite-redesign pull request #1144
Opened 2022-05-10 11:14 UTC by pauline-n

The url env was not working, updating it with he current url that is working

2022-05-10 14:27 UTC, edwinmp requested changes

2022-05-10 14:27 UTC, edwinmp commented on .gitignore
> +package-lock.json
Nope ... please don't ignore package-lock.

2022-05-11 06:09 UTC, pauline-n commented on .gitignore
> +package-lock.json
Done

2022-05-11 06:52 UTC, edwinmp approved these changes

2022-05-11 06:52 UTC, merged