Fix | Copying Pages
devinit/DIwebsite-redesign pull request #1226
Opened 2022-09-22 09:01 UTC by davidebukali

#1223

2022-09-22 09:22 UTC, edwinmp requested changes
Why are the options uppercase to begin with? Couldn't changing them to lowercase fix it? Seems overkill to create a hook simply to fix a wonky coding choice.

2022-09-22 09:27 UTC, davidebukali commented
@edwinmp changing to lower case requires a migration which may affect existing pages and also need a data migration to update. This seemed a shorter route. If few pages have used the feature, I think lowercasing would be ideal.

2022-09-22 09:55 UTC, edwinmp commented
> @edwinmp changing to lower case requires a migration which may affect existing pages and also need a data migration to update. This seemed a shorter route. If few pages have used the feature, I think lowercasing would be ideal.

This just went live last week, by accident ... I'm sure we can afford a cleaner solution with no disruption. I'm absolutely certain that the other options (not manual) haven't been used. The original ticket is still in review and hasn't been commented on.

2022-09-22 09:55 UTC, edwinmp commented
No data migration needed.

2022-09-22 16:55 UTC, edwinmp requested changes

2022-09-22 16:55 UTC, edwinmp commented on di_website/publications/mixins.py
> +    ('Topic', 'Topic')
This still has upper case letters in it.

2022-09-23 08:59 UTC, edwinmp approved these changes

2022-09-23 09:04 UTC, merged