Feature|Podcast Subscription
devinit/DIwebsite-redesign pull request #1230
Opened 2022-09-28 10:42 UTC by ThatcherK

ticket #1194

2022-09-28 12:04 UTC, edwinmp requested changes

2022-09-28 12:04 UTC, edwinmp commented on di_website/templates/publications/tags/podcast_platforms.html
> +  {% endif %}
As far as I can tell, the only difference here are the contents of the link tag. So repeating the link tag is redundant. Basically, put the `if` statement within the link tag.

2022-09-28 14:35 UTC, edwinmp commented
So there was a difference I hadn't seen ... If I request a change that results into more code (like this one), please let me know. I'd likely never go for it and it'll save you from reverting. Basically, I'm not infallible. Please revert & I'll approve.

2022-09-28 14:47 UTC, ThatcherK commented
done @edwinmp

2022-09-29 09:13 UTC, edwinmp submitted a review, later dismissed

2022-09-29 09:14 UTC, edwinmp approved these changes

2022-09-29 09:19 UTC, merged