Add django-slack logger
devinit/DIwebsite-redesign pull request #1268
Opened 2022-11-29 07:27 UTC by ThatcherK

2023-01-10 07:45 UTC, wakibi requested changes

2023-01-10 07:45 UTC, wakibi commented on requirements.txt
> +git+https://github.com/devinit/slack_messages.git
Can you investigate possibility of having our own NPM repo where we can publish this, as opposed to pulling it from Github directly?

2023-01-10 07:45 UTC, wakibi commented on requirements.txt
> +git+https://github.com/devinit/slack_messages.git
Also, can you investigate possibility of using (jinja2) templates to make the text more rich and formatted?

2023-01-10 15:39 UTC, edwinmp requested changes

2023-01-10 15:39 UTC, edwinmp commented on di_website/settings/base.py
> +    # 'django_slack',
Remove this entirely.

2023-01-23 07:02 UTC, edwinmp commented
@ThatcherK @wakibi is this done? If so, are we good to remove the intentional bug and merge this?

2023-01-23 07:04 UTC, ThatcherK commented
No It's not, there's a bug that I haven't yet figured out

2023-01-23 17:51 UTC, edwinmp commented
Changing it to draft until you're free to get back to it.

2023-04-02 08:51 UTC, closed without merging