Feature | Short Publication Accessibility
devinit/DIwebsite-redesign pull request #1287
Opened 2023-01-09 08:04 UTC by davidebukali

Ticket #1285

2023-01-09 15:55 UTC, ThatcherK requested changes
There are still some alerts and errors I see that could be fixed

1. In the image below, the description text in description lists is small

<img width="596" alt="Screenshot 2023-01-09 at 14 54 45" src="https://user-images.githubusercontent.com/32189973/211346057-2ac59377-83e5-4c99-b7ee-f16678619026.png">
2. In the footer
<img width="1440" alt="Screenshot 2023-01-09 at 18 21 25" src="https://user-images.githubusercontent.com/32189973/211346458-93c56039-bbbe-425c-94c8-990e5fde45f5.png">

3. Am also getting this alert for images in the case study infographic as well as the stand alone infographic image
<img width="1426" alt="Screenshot 2023-01-09 at 18 28 55" src="https://user-images.githubusercontent.com/32189973/211346698-7d7a294e-1013-425c-a303-f0329ddca6bf.png">

4. I have also noted that when orange, blue, yellow, and green are used as a theme colour, we have multiple contrast errors. I wonder what decision will be taken on that?

2023-01-18 08:22 UTC, ThatcherK commented
Good job with the contrast errors! 
Just one alert I missed here, that can easily be resolved
<img width="1057" alt="Screenshot 2023-01-18 at 11 16 50" src="https://user-images.githubusercontent.com/32189973/213119920-78272c5e-6023-4333-843d-d583aca3c350.png">

2023-01-18 10:05 UTC, edwinmp commented
@davidebukali I hope this has covered every existing `StreamField` type.

2023-01-24 12:29 UTC, ThatcherK approved these changes

2023-01-24 12:51 UTC, merged