add blockquote functionality to short publication and publication pages
devinit/DIwebsite-redesign pull request #889
Opened 2020-09-02 12:55 UTC by mariamiah

2020-09-02 13:13 UTC, edwinmp commented
Did you test on the actual pages this will affect and made sure it appears as expected? One vital feature is that the `blockquote` must take on the colour of the parent publication. This is likely working by default, but need to know that it's been tested.

2020-09-02 13:15 UTC, edwinmp commented
Also, I have a strong feeling that this feature should come with migrations.

2020-09-02 13:31 UTC, mariamiah commented
> Did you test on the actual pages this will affect and made sure it appears as expected (not just on the admin side)? One vital feature is that the `blockquote` must take on the colour of the parent publication. This is likely working by default, but need to know that it's been tested.

Yes, tested with the appendix, chapter, foreword, summary and short publication pages and they all appear as expected

2020-09-02 15:01 UTC, edwinmp commented
![image](https://user-images.githubusercontent.com/5672438/91999900-95349900-ed45-11ea-8fab-004594fbdfb0.png)

This doesn't match the design ... these blockquotes are too wide ... yes, that's important ... comms reviewers are that particular, so please make sure it matches the designs in the pattern library.
I suggest u don't edit this block's template as it's already being used as it is elsewhere ... provide another template that fits this use case. https://docs.wagtail.io/en/v2.9/topics/streamfield.html#template-rendering

2020-09-02 20:03 UTC, edwinmp requested changes

2020-09-02 20:03 UTC, edwinmp commented on di_website/publications/blocks.py
> +
This is an entirely new block, which is redundant ... u only need to specify a different template when using the already existing block i.e `BlockQuote(template='path/to/template')`

2020-09-03 05:56 UTC, edwinmp approved these changes
Fixed the uncentered view and added the missing migrations

2020-09-03 06:18 UTC, merged